"""Orchestration-local bounded review context helpers."""

from src.orchestration.context.context_packets import (
    ContextPacket,
    ContextSection,
    build_critique_packet,
    build_critique_probe_packet,
    build_critiquer_packet,
    build_critique_revision_shard_packet,
    build_draft_planner_packet,
    build_intent_extractor_packet,
    build_mandate_synthesizer_packet,
    build_plan_critic_packet,
    build_plan_revision_packet,
    build_reflection_packet,
    build_verifier_generator_packet,
    classes_introduced_in_diff,
    enrich_intent_summary_with_diff_scope,
    enforce_packet_budget,
    format_pr_context_section,
    merge_probe_flags,
    packet_to_prompt_sections,
    packet_to_storage_dict,
    pr_context_from_state,
    render_packet_plaintext,
    section_content_from_storage,
    spec_risks_excerpt_for_prompt,
    surface_inventory_from_state,
)
from src.orchestration.context.review_context import (
    BoundedReviewContextFulfiller,
    LazyReviewContextProvider,
)
from src.orchestration.context.task_evidence import (
    build_task_evidence,
    claim_slices_for_candidates,
    code_slice_from_task_evidence,
)
from src.orchestration.context.surface_ledger import (
    build_surface_ledger_from_diff,
    compact_surface_ledger_json,
    surface_ledger_from_state,
)

__all__ = [
    "BoundedReviewContextFulfiller",
    "LazyReviewContextProvider",
    "ContextPacket",
    "ContextSection",
    "build_critique_packet",
    "build_critique_probe_packet",
    "build_critiquer_packet",
    "build_critique_revision_shard_packet",
    "build_draft_planner_packet",
    "build_intent_extractor_packet",
    "build_mandate_synthesizer_packet",
    "build_plan_critic_packet",
    "build_plan_revision_packet",
    "build_reflection_packet",
    "build_verifier_generator_packet",
    "classes_introduced_in_diff",
    "enrich_intent_summary_with_diff_scope",
    "enforce_packet_budget",
    "format_pr_context_section",
    "pr_context_from_state",
    "surface_inventory_from_state",
    "build_surface_ledger_from_diff",
    "compact_surface_ledger_json",
    "surface_ledger_from_state",
    "merge_probe_flags",
    "packet_to_prompt_sections",
    "packet_to_storage_dict",
    "render_packet_plaintext",
    "section_content_from_storage",
    "spec_risks_excerpt_for_prompt",
    "build_task_evidence",
    "claim_slices_for_candidates",
    "code_slice_from_task_evidence",
]
